### ISSUE TITLE
Create mockups/wireframes

### ISSUE THREAD

**Issue by HunteRoi** [Section-IG/IGBot#2]
As the application is supposed to have a web interface, it is important to create mockups and/or wireframes so that we know what will be the result of the work on the React side of the application.

Different tools exist to create this kind of stuff. It is important to stick to one:
- [Figma](https://www.figma.com/)
- [Uizard](https://uizard.io/)
- [Sketch](https://www.sketch.com/)
- [Visual Paradigm](https://www.visual-paradigm.com/)
- [Balsamiq Wireframes](https://balsamiq.com/)

Let's discuss the choice of tool and how we should be the interface in the comment section of this issue!

**Comment by HunteRoi** [comment]
@Arsero is it possible that you start working on this please?

**Comment by Arsero** [comment]
@HunteRoi I'm able to start with Figma.

**Comment by HunteRoi** [comment]
I will let you handle all this then!

**Comment by HunteRoi** [comment]
For the features we would like to have on the website, here is a few ideas for you:
- a dashboard page to configure a server that hasn't been yet
- a "ban appeal" page for users who have been banned from a guild but want to have it removed
- a stats page with charts, tables etc about the inner activity of the guild

If you have other ideas, feel free to mention me !
